apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jcasc-seed-job
  namespace: jenkins
  labels:
    jenkins-jenkins-config: "true"
data:
  jcasc.yaml: |
    jobs:
    - script: >
        job('seed-job') {
          description('Seed job to create multibranch jobs via DSL')
          scm {
            git {
              remote {
                url('https://github.com/DevSecOps-homelab/jenkins-core')
                credentials('github-access-token')
              }
              branch('main')
            }
          }
          triggers {
            scm('H/5 * * * *')
          }
          steps {
            dsl {
              external('jobs/*.groovy')
              removeAction('DELETE')
              removeViewAction('DELETE')
            }
          }
        }