apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-jcasc-main
  namespace: jenkins
  labels:
    jenkins-jenkins-config: "true"
data:
  jcasc.yaml: |
    jenkins:
      disabledAdministrativeMonitors:
      - hudson.diagnosis.ReverseProxySetupMonitor
      numExecutors: 1
      mode: NORMAL
      markupFormatter:
        plainText: {}
      clouds:
        - kubernetes:
            name: "kubernetes"
            serverUrl: "https://kubernetes.default"
            jenkinsUrl: "http://jenkins.jenkins.svc.cluster.local:8080"
            jenkinsTunnel: "jenkins-agent.jenkins.svc.cluster.local:50000"
            containerCapStr: "10"
            namespace: "jenkins"
    
    security:
      apiToken:
        creationOfLegacyTokenEnabled: false
        tokenGenerationOnCreationEnabled: false
        usageStatisticsEnabled: true
    
    appearance:
      prism:
        theme: PRISM
      themeManager:
        disableUserThemes: false
        theme: "darkSystem"