apiVersion: v1
kind: ConfigMap
metadata:
  name: buildkitd-config
  namespace: buildkit
data:
  buildkitd.toml: |
    [registry."harbor-harbor-core.harbor.svc.cluster.local"]
    http = true

    [worker.oci]
    gc = true