apiVersion: v1
kind: Service
metadata:
  name: buildkit-service
spec:
  type: ClusterIP
  ports:
    - port: 1234
      targetPort: tcp
      protocol: TCP
      name: tcp
  selector:
    app.kubernetes.io/name: buildkit-service
    app.kubernetes.io/instance: buildkit
