apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml

helmCharts:
  - name: sonarqube
    releaseName: sonarqube
    version: 2025.3.1
    repo: https://SonarSource.github.io/helm-chart-sonarqube
    namespace: sonarqube
    valuesFile: values.yaml