apiVersion: v1
kind: Secret
metadata:
  name: buildkit-s3-secret
  namespace: buildkit
data:
  AWS_ACCESS_KEY_ID: BASE64_ENCODED_PLACEHOLDER
  AWS_SECRET_ACCESS_KEY: BASE64_ENCODED_PLACEHOLDER
  AWS_REGION: BASE64_ENCODED_PLACEHOLDER
  AWS_BUCKET: BASE64_ENCODED_PLACEHOLDER