apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - harbor-ingress.yaml

helmCharts:
  - name: harbor
    releaseName: harbor
    version: 1.3.2
    repo: https://helm.goharbor.io
    namespace: harbor
    valuesFile: values.yaml