apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: minio
    releaseName: minio
    version: 5.4.0
    repo: https://charts.min.io/
    namespace: minio
    valuesFile: values.yaml

resources:
  - namespace.yaml